#ifndef COREINTEGRATIONFRAME_GLOBAL_H
#define COREINTEGRATIONFRAME_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COREINTEGRATIONFRAME_LIBRARY)
#  define COREINTEGRATIONFRAMESHARED_EXPORT Q_DECL_EXPORT
#else
#  define COREINTEGRATIONFRAMESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COREINTEGRATIONFRAME_GLOBAL_H
